/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch design system — exact match
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#160d57",
        "surface-container-lowest": "#0e0e12",
        "inverse-surface": "#e5e1e8",
        "primary-fixed-dim": "#c5c0ff",
        background: "#131317",
        "on-secondary-fixed": "#211b00",
        "on-tertiary-container": "#ff462a",
        "on-primary-fixed-variant": "#423e84",
        "surface-container": "#201f24",
        "outline-variant": "#474550",
        "inverse-on-surface": "#313035",
        "on-primary": "#2c266c",
        error: "#ffb4ab",
        "on-tertiary": "#660700",
        "secondary-container": "#fbdd00",
        "surface-bright": "#3a383e",
        "on-background": "#e5e1e8",
        "on-error": "#690005",
        "secondary-fixed": "#ffe33d",
        "surface-container-low": "#1c1b20",
        "surface-variant": "#353439",
        "tertiary-fixed-dim": "#ffb4a6",
        "surface-tint": "#c5c0ff",
        "tertiary-container": "#4f0400",
        secondary: "#fff9ec",
        "error-container": "#93000a",
        outline: "#928f9b",
        "on-tertiary-fixed-variant": "#900e00",
        "on-surface": "#e5e1e8",
        "surface-container-high": "#2a292e",
        surface: "#131317",
        "tertiary-fixed": "#ffdad4",
        "on-secondary-container": "#6f6100",
        "on-surface-variant": "#c8c5d2",
        "surface-dim": "#131317",
        tertiary: "#ffb4a6",
        "secondary-fixed-dim": "#e2c600",
        "inverse-primary": "#5a569d",
        "primary-container": "#1f185f",
        "primary-fixed": "#e3dfff",
        "on-primary-container": "#8883ce",
        "on-secondary-fixed-variant": "#524700",
        primary: "#c5c0ff",
        "surface-container-highest": "#353439",
        "on-secondary": "#383000",
        "on-tertiary-fixed": "#3f0300",

        // Brand override colors (override-primary/secondary/tertiary from Stitch project)
        "brand-navy": "#1F185F",
        "brand-yellow": "#FDDE00",
        "brand-red": "#D12209",
        "brand-green": "#009A39",

        // Light editorial palette
        "page": "#F7F6F4",
        "page-alt": "#FFFFFF",
        "ink": "#0D0C1A",
        "stone": "#4B4B5A",
        "dust": "#9095A0",
        "hairline": "#E2E1EA",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "80px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
        base: "8px",
      },
      fontFamily: {
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Anton", "sans-serif"],
        "headline-sm": ["Anton", "sans-serif"],
        "headline-xl-mobile": ["Anton", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Anton", "sans-serif"],
        "label-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Anton", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Anton", "sans-serif"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "32px", letterSpacing: "0", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "headline-xl-mobile": ["56px", { lineHeight: "56px", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["80px", { lineHeight: "80px", letterSpacing: "0", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg-mobile": ["36px", { lineHeight: "36px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "48px", letterSpacing: "0", fontWeight: "400" }],
      },
      backgroundImage: {
        "pitch-texture":
          "radial-gradient(circle at center, rgba(255,255,255,0.03) 1px, transparent 1px)",
      },
      backgroundSize: {
        "pitch-grid": "24px 24px",
      },
      keyframes: {
        bounceArrow: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(8px)" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(28px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-24px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% center" },
          "100%": { backgroundPosition: "200% center" },
        },
      },
      animation: {
        "bounce-arrow": "bounceArrow 1.6s ease-in-out infinite",
        "fade-in-up": "fadeInUp 0.65s ease-out forwards",
        "fade-in": "fadeIn 0.65s ease-out forwards",
        "slide-in-left": "slideInLeft 0.65s ease-out forwards",
        "scale-in": "scaleIn 0.5s ease-out forwards",
      },
    },
  },
  plugins: [],
};
